# To execute this docker-compose yml file use `docker-compose -f <file_name> up`
# Add the `-d` flag at the end for detached execution
version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.14.0-helium
    container_name: selenium-hub
    environment:
      - GRID_MAX_SESSION=8
      - GRID_NEW_SESSION_WAIT_TIMEOUT=60      
    ports:
      - "4444:4444"
  chrome1:
    image: selenium/node-chrome:3.14.0-helium
    volumes:
      - /dev/shm:/dev/shm
    links:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - GRID_MAX_SESSION
  chrome2:
    image: selenium/node-chrome:3.14.0-helium
    volumes:
      - /dev/shm:/dev/shm
    links:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  chrome3:
    image: selenium/node-chrome:3.14.0-helium
    volumes:
      - /dev/shm:/dev/shm
    links:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  chrome4:
    image: selenium/node-chrome:3.14.0-helium
    volumes:
      - /dev/shm:/dev/shm
    links:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  chrome5:
    image: selenium/node-chrome:3.14.0-helium
    volumes:
      - /dev/shm:/dev/shm
    links:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444      
  chrome6:
    image: selenium/node-chrome:3.14.0-helium
    volumes:
      - /dev/shm:/dev/shm
    links:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444      
  chrome7:
    image: selenium/node-chrome:3.14.0-helium
    volumes:
      - /dev/shm:/dev/shm
    links:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444      
  chrome8:
    image: selenium/node-chrome:3.14.0-helium
    volumes:
      - /dev/shm:/dev/shm
    links:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444            